# Generated by Django 2.1.3 on 2019-04-25 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(default=8080808080)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(default=8080808080, max_length=10)),
                ('pin_code', models.IntegerField(default=500005)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='client_user',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='workerapp.UserDetails'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='worker',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='workerapp.WorkerDetails'),
        ),
    ]
