# Generated by Django 2.1.3 on 2019-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0002_auto_20190425_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdetails',
            name='profession',
            field=models.CharField(default='', max_length=20),
        ),
    ]
