# Generated by Django 2.1.3 on 2019-04-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0003_workerdetails_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
