# Generated by Django 2.1.3 on 2019-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0004_auto_20190426_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='address',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
